<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>재고·입출고 현황 | 앙사모 ERP</title><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/material.css"></head><body>
<jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace">
<section class="page-heading"><div><p class="eyebrow">INVENTORY</p><h1>재고·입출고 현황</h1><p>품목별 현재 재고와 최근 입고·출고·반품·조정 이력을 확인합니다.</p></div></section>
<section class="notice"><span class="material-symbols-outlined">inventory_2</span><p><strong>재고 기준</strong> 현재 수량은 <code>inventory.current_qty</code>를 기준으로 표시하며 모든 변동은 입출고 이력에서 확인할 수 있습니다.</p></section>
<section class="panel inventory-search"><form method="get" action="${pageContext.request.contextPath}/material/inventory"><label>품목 검색<input type="search" name="keyword" value="${keyword}" placeholder="품목코드 또는 품목명"></label><label>부족 기준 수량<input type="number" name="maxQty" min="0" step="0.001" value="${maxQty}" placeholder="예: 10"></label><label>입출고 유형<select name="movementType"><option value="">전체 유형</option><option value="IN" ${movementType eq 'IN' ? 'selected' : ''}>입고</option><option value="OUT" ${movementType eq 'OUT' ? 'selected' : ''}>출고</option><option value="RETURN" ${movementType eq 'RETURN' ? 'selected' : ''}>반품</option></select></label><button class="action-button" type="submit">조회</button><a class="text-button" href="${pageContext.request.contextPath}/material/inventory">초기화</a></form></section>
<c:if test="${not empty success}"><div class="flash success"><c:out value="${success}"/></div></c:if><c:if test="${not empty error}"><div class="flash error"><c:out value="${error}"/></div></c:if>
<section class="panel inventory-adjust-panel"><div><p class="eyebrow">INVENTORY ADJUSTMENT</p><h2>재고 설정·수동 조정</h2><p>최초 설정은 재고 행을 자동 생성하며, 감소 수량은 음수로 입력합니다. 조정 사유는 필수입니다.</p></div><form method="post" action="${pageContext.request.contextPath}/material/inventory/adjust"><label>부서 ID<input type="number" name="departmentId" min="1" required></label><label>자재 품목<select name="itemId" required><option value="">품목 선택</option><c:forEach items="${materials}" var="material"><option value="${material.itemId}"><c:out value="${material.itemCode}"/> · <c:out value="${material.itemName}"/></option></c:forEach></select></label><label>조정 수량<input type="number" name="adjustmentQty" step="0.001" placeholder="예: 10 또는 -3" required></label><label>조정 사유<input type="text" name="memo" maxlength="500" placeholder="실사 조정 사유" required></label><button class="action-button" type="submit">재고 조정</button></form></section>
<section class="panel table-panel"><div class="panel-header"><h2>품목별 현재 재고</h2><span class="list-count">${inventory.size()}개</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>품목코드</th><th>품목명</th><th>규격</th><th>부서</th><th>현재 수량</th><th>단위</th><th>품목 상태</th><th>갱신 일시</th></tr></thead><tbody>
<c:forEach items="${inventory}" var="row"><tr class="${row.currentQty <= 0 ? 'low-stock-row' : ''}"><td><strong><c:out value="${row.itemCode}"/></strong></td><td><c:out value="${row.itemName}"/></td><td><c:out value="${empty row.spec ? '-' : row.spec}"/></td><td>${row.departmentId}</td><td><strong><fmt:formatNumber value="${row.currentQty}" pattern="#,#00.###"/></strong><c:if test="${row.currentQty <= 0}"><span class="low-stock-label">부족</span></c:if></td><td><c:out value="${row.unit}"/></td><td><span class="state-badge ${row.active ? 'enabled' : 'disabled'}">${row.active ? '사용' : '사용 중지'}</span></td><td><c:out value="${row.updatedAtText}"/></td></tr></c:forEach>
<c:if test="${empty inventory}"><tr><td colspan="8" class="empty-cell">등록된 재고가 없습니다.</td></tr></c:if></tbody></table></div></section>
<section class="panel table-panel movement-panel"><div class="panel-header"><h2>최근 입출고 이력</h2><span class="list-count">최근 ${movements.size()}건</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>이력</th><th>처리 일시</th><th>유형</th><th>품목</th><th>수량</th><th>부서</th><th>참조 업무</th><th>처리자</th><th>메모</th></tr></thead><tbody>
<c:forEach items="${movements}" var="row"><tr><td>SM-${row.movementId}</td><td><c:out value="${row.createdAtText}"/></td><td><span class="movement-badge movement-${row.movementType}"><c:choose><c:when test="${row.movementType eq 'IN'}">입고</c:when><c:when test="${row.movementType eq 'OUT'}">출고</c:when><c:when test="${row.movementType eq 'RETURN'}">반품</c:when><c:otherwise>조정</c:otherwise></c:choose></span></td><td><strong><c:out value="${row.itemName}"/></strong><br><span class="hint"><c:out value="${row.itemCode}"/></span></td><td><fmt:formatNumber value="${row.quantity}" pattern="#,#00.###"/> <c:out value="${row.unit}"/></td><td>${row.departmentId}</td><td><c:out value="${empty row.referenceType ? '-' : row.referenceType}"/><c:if test="${not empty row.referenceId}"> #${row.referenceId}</c:if></td><td>${row.processedBy}</td><td><c:out value="${empty row.memo ? '-' : row.memo}"/></td></tr></c:forEach>
<c:if test="${empty movements}"><tr><td colspan="9" class="empty-cell">입출고 이력이 없습니다.</td></tr></c:if></tbody></table></div></section>
</main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script></body></html>
