<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>출고 관리 | 앙사모 ERP</title><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css?v=20260804-4"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/material.css?v=20260804-3"></head>
<body><c:set var="headerTitle" value="자재 출고 프로세스" scope="request"/><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace">
	<section class="page-heading"><div><p class="eyebrow">MATERIAL ISSUE</p><h1>자재 출고 관리</h1><p>생산 요청에 따라 재고를 파악하고 자재 불출, 출고 처리, 재고 및 금액 산출을 수행합니다.</p></div></section>
	<c:if test="${not empty success}"><div class="flash success">${success}</div></c:if><c:if test="${not empty error}"><div class="flash error">${error}</div></c:if>
	<section class="issue-flow"><div class="current"><b>1</b><span>생산 요청</span></div><i>→</i><div><b>2</b><span>가용 재고 파악</span></div><i>→</i><div><b>3</b><span>자재 불출</span></div><i>→</i><div><b>4</b><span>출고 처리</span></div><i>→</i><div><b>5</b><span>재고 산출</span></div><i>→</i><div><b>6</b><span>재고금액 현황</span></div></section>
	<section class="notice"><span class="notice-mark">ⓘ</span><p><strong>출고 기준:</strong> 요청 수량과 실물 불출 수량을 확인한 후 가용 재고 범위에서 처리합니다. 저장 즉시 출고 수량, 재고 수량, 재고 금액과 이력이 자동 반영됩니다.</p></section>

	<section class="panel issue-filter"><div><p class="eyebrow">SEARCH</p><h2>출고 자재 빠른 검색</h2></div><form method="get" action="${pageContext.request.contextPath}/material/issues"><label>시작일<input type="date" name="fromDate" value="${fromDate}"></label><label>종료일<input type="date" name="toDate" value="${toDate}"></label><label>품목<select name="itemCode"><option value="">전체 품목</option><c:forEach items="${valueReport}" var="stock"><option value="${stock.itemCode}" ${itemCode == stock.itemCode ? 'selected' : ''}>${stock.itemName}</option></c:forEach></select></label><label>처리 상태<select name="status"><option value="">전체 상태</option><option value="REQUESTED" ${status == 'REQUESTED' ? 'selected' : ''}>출고 요청</option><option value="PARTIAL" ${status == 'PARTIAL' ? 'selected' : ''}>부분 출고</option><option value="COMPLETED" ${status == 'COMPLETED' ? 'selected' : ''}>출고 완료</option></select></label><button class="action-button" type="submit">조회</button></form></section>

	<section class="issue-request-grid">
	<c:forEach items="${issues}" var="row"><article class="panel issue-card">
		<div class="issue-card-head"><div><p class="eyebrow">ISSUE IS-${row.issueId}</p><h2>${row.itemName}</h2><p>${row.itemCode} · 생산요청 PR-${row.requestId}</p></div><span class="state-badge ${row.status == 'COMPLETED' ? 'enabled' : 'disabled'}">${row.status}</span></div>
		<div class="issue-facts"><div><span>소요 공정</span><strong>${empty row.inputProcess ? '-' : row.inputProcess}</strong></div><div><span>생산 일정</span><strong>${row.scheduleDate}</strong></div><div><span>요청 수량</span><strong>${row.releaseQty}</strong></div><div><span>기출고</span><strong>${row.issueQty}</strong></div><div><span>가용 재고</span><strong>${row.availableQty}</strong></div><div><span>재고 금액</span><strong>${row.stockValue}</strong></div></div>
		<c:choose><c:when test="${row.status == 'COMPLETED'}"><div class="issue-complete">출고 완료 · ${row.issuedAt}</div></c:when><c:otherwise><form class="issue-process-form" method="post" action="${pageContext.request.contextPath}/material/issues/process"><input type="hidden" name="issueId" value="${row.issueId}"><label>이번 출고 수량<input type="number" name="qty" min="1" max="${row.releaseQty - row.issueQty}" value="${row.releaseQty - row.issueQty}" required></label><div><strong>출고 후 예상 재고</strong><span>${row.availableQty} - 출고 수량</span></div><button class="action-button" type="submit">실물 확인 및 출고 처리</button></form></c:otherwise></c:choose>
	</article></c:forEach><c:if test="${empty issues}"><article class="panel empty-process"><strong>조건에 맞는 출고 요청이 없습니다.</strong><p>생산부서에서 자재 소모 요청을 등록하면 표시됩니다.</p></article></c:if>
	</section>

	<section class="panel value-report"><div class="panel-header"><div><p class="eyebrow">INVENTORY VALUE REPORT</p><h2>재고 수량 및 재고 금액 현황</h2></div><button class="text-button" type="button" onclick="window.print()">리포트 인쇄</button></div><div class="table-scroll"><table class="data-table"><thead><tr><th>품목</th><th>기본 재고</th><th>기간 출고</th><th>가용 재고</th><th>산출 재고</th><th>공급가격</th><th>재고금액</th><th>산출일</th></tr></thead><tbody><c:forEach items="${valueReport}" var="row"><tr><td>${row.itemName}<br><span class="hint">${row.itemCode}</span></td><td>${row.baseQty}</td><td>${row.periodIssueQty}</td><td><strong>${row.availableQty}</strong></td><td>${row.calcQty}</td><td>${row.unitPrice}</td><td><strong>${row.stockValue}</strong></td><td>${row.updatedAt}</td></tr></c:forEach><c:if test="${empty valueReport}"><tr><td colspan="8" class="empty-cell">재고 산출 자료가 없습니다.</td></tr></c:if></tbody></table></div></section>
</main></div><script src="${pageContext.request.contextPath}/resources/js/common.js?v=20260804-5"></script></body></html>
