<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>계약 관리 | 앙사모 ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/purchase.css"></head><body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace">
<section class="page-heading"><div><p class="eyebrow">PURCHASE CONTRACT</p><h1>계약 관리</h1><p>선정 견적과 확정 계약조건을 관리합니다.</p></div></section>
<c:set var="contractCount" value="0"/>
<c:forEach items="${procurements}" var="p"><c:if test="${p.status == 'SELECTED' or p.status == 'CONTRACTED' or p.status == 'ORDERED' or p.status == 'IN_PROGRESS' or p.status == 'SHIPPED' or p.status == 'RECEIVED' or p.status == 'CLOSED'}"><c:set var="contractCount" value="${contractCount + 1}"/></c:if></c:forEach>
<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">CONTRACT STATUS</p><h2>계약 진행 현황</h2></div><span class="list-count">${contractCount}건</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>계약</th><th>품목</th><th>협력회사</th><th>수량</th><th>단가</th><th>계약 조건</th><th>현재 상태</th><th>상세</th></tr></thead><tbody>
<c:forEach items="${procurements}" var="p"><c:if test="${p.status == 'SELECTED' or p.status == 'CONTRACTED' or p.status == 'ORDERED' or p.status == 'IN_PROGRESS' or p.status == 'SHIPPED' or p.status == 'RECEIVED' or p.status == 'CLOSED'}"><tr><td>CT-${p.procurementId}</td><td><c:out value="${p.itemName}"/></td><td><c:out value="${p.selectedVendorName}"/></td><td>${p.orderQty} ${p.unit}</td><td>${p.unitPrice}</td><td><c:out value="${p.status == 'SELECTED' ? '확정 대기' : '확정'}"/></td><td><span class="state-badge enabled">${p.status}</span></td><td><a class="purchase-action-button" href="${pageContext.request.contextPath}/purchase/procurements/${p.procurementId}">확인</a></td></tr></c:if></c:forEach>
<c:if test="${contractCount == 0}"><tr><td colspan="8" class="empty-cell">진행 중인 계약이 없습니다.</td></tr></c:if>
</tbody></table></div></section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script></body></html>
