<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>구매 현황 | 앙사모 ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/purchase.css"></head><body>
<jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace">
<section class="page-heading"><div><p class="eyebrow">PURCHASE DASHBOARD</p><h1>구매 현황</h1><p>조달·견적·계약·발주 진행 상황을 요약합니다.</p></div></section>
<c:set var="requested" value="0"/><c:set var="quouting" value="0"/><c:set var="contracted" value="0"/><c:set var="ordered" value="0"/>
<c:forEach items="${procurements}" var="p"><c:if test="${p.status == 'REQUESTED'}"><c:set var="requested" value="${requested + 1}"/></c:if><c:if test="${p.status == 'QUOTING'}"><c:set var="quouting" value="${quouting + 1}"/></c:if><c:if test="${p.status == 'SELECTED' or p.status == 'CONTRACTED'}"><c:set var="contracted" value="${contracted + 1}"/></c:if><c:if test="${p.status == 'ORDERED' or p.status == 'IN_PROGRESS' or p.status == 'SHIPPED'}"><c:set var="ordered" value="${ordered + 1}"/></c:if></c:forEach>
<section class="purchase-dashboard-grid"><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/procurements"><p class="eyebrow">PROCUREMENT</p><h2>${requested}</h2><p>조달 요청</p></a><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/quotes"><p class="eyebrow">QUOTE</p><h2>${quouting}</h2><p>견적 진행</p></a><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/contracts"><p class="eyebrow">CONTRACT</p><h2>${contracted}</h2><p>선정·계약</p></a><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/orders"><p class="eyebrow">ORDER</p><h2>${ordered}</h2><p>발주 진행</p></a></section>
<section class="panel table-panel"><div class="panel-header"><h2>최근 조달업무</h2><span class="list-count">${procurements.size()}건</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>조달</th><th>품목</th><th>업체</th><th>상태</th><th>필요일</th></tr></thead><tbody><c:forEach items="${procurements}" var="p" begin="0" end="9"><tr><td><a href="${pageContext.request.contextPath}/purchase/procurements/${p.procurementId}">P-${p.procurementId}</a></td><td><c:out value="${p.itemName}"/></td><td><c:out value="${p.selectedVendorName}" default="미선정"/></td><td><span class="state-badge enabled"><c:out value="${p.status}"/></span></td><td>${p.requiredDate}</td></tr></c:forEach><c:if test="${empty procurements}"><tr><td colspan="5" class="empty-cell">조달업무가 없습니다.</td></tr></c:if></tbody></table></div></section>
</main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script></body></html>
