<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ taglib prefix="my" tagdir="/WEB-INF/tags" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>구매 현황 | 앙사모 ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/purchase.css">
<style>
    .quick-actions { display:flex; gap:10px; }
    .quick-actions a { padding:9px 13px; color:#fff; background:var(--blue); border-radius:6px; font-size:12px; font-weight:700; }
    .purchase-dashboard-card.warning h2 { color:#b42318; }
    .dashboard-panels { display:grid; grid-template-columns:1fr 1fr; gap:18px; }
    @media (max-width:900px) { .dashboard-panels { grid-template-columns:1fr; } }
</style>
</head><body>
<jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace">
<section class="page-heading"><div><p class="eyebrow">PURCHASE DASHBOARD</p><h1>구매 현황</h1><p>조달·견적·계약·발주 진행 상황을 요약합니다.</p></div>
<div class="quick-actions"><a href="${pageContext.request.contextPath}/purchase/shortages">연계 조회</a><a href="${pageContext.request.contextPath}/purchase/vendors">협력회사 관리</a></div>
</section>
<section class="purchase-dashboard-grid"><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/procurements"><p class="eyebrow">TOTAL</p><h2><c:out value="${summary.totalProcurementCount}"/></h2><p>전체 조달업무</p></a><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/quotes"><p class="eyebrow">QUOTE</p><h2><c:out value="${summary.quotingCount}"/></h2><p>견적 진행</p></a><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/orders"><p class="eyebrow">ORDER</p><h2><c:out value="${summary.orderedCount}"/></h2><p>발주 완료</p></a><a class="panel purchase-dashboard-card" href="${pageContext.request.contextPath}/purchase/receivings"><p class="eyebrow">SHIPPED</p><h2><c:out value="${summary.shippedWaitingCount}"/></h2><p>입고 대기</p></a><a class="panel purchase-dashboard-card warning" href="${pageContext.request.contextPath}/purchase/shortages"><p class="eyebrow">SHORTAGE</p><h2><c:out value="${summary.shortageWaitingCount}"/></h2><p>조달 미착수 부족건</p></a></section>
<div class="dashboard-panels">
<section class="panel table-panel"><div class="panel-header"><h2>최근 조달업무</h2><span class="list-count">${procurements.size()}건</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>조달</th><th>품목</th><th>업체</th><th>상태</th><th>필요일</th></tr></thead><tbody><c:forEach items="${procurements}" var="p" begin="0" end="9"><tr><td><a href="${pageContext.request.contextPath}/purchase/procurements/${p.procurementId}">P-${p.procurementId}</a></td><td><c:out value="${p.itemName}"/></td><td><c:out value="${p.selectedVendorName}" default="미선정"/></td><td><my:procurementStatus status="${p.status}"/></td><td>${p.requiredDate}</td></tr></c:forEach><c:if test="${empty procurements}"><tr><td colspan="5" class="empty-cell">조달업무가 없습니다.</td></tr></c:if></tbody></table></div></section>
<section class="panel table-panel"><div class="panel-header"><h2>최근 견적 현황</h2><span class="list-count">${quotes.size()}건</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>조달</th><th>품목</th><th>업체</th><th>단가</th><th>상태</th></tr></thead><tbody><c:forEach items="${quotes}" var="q" begin="0" end="9"><tr><td><a href="${pageContext.request.contextPath}/purchase/procurements/${q.procurementId}">P-${q.procurementId}</a></td><td><c:out value="${q.itemName}"/></td><td><c:out value="${q.vendorName}"/></td><td><c:choose><c:when test="${not empty q.unitPrice}"><fmt:formatNumber value="${q.unitPrice}" pattern="#,#00.##"/></c:when><c:otherwise>-</c:otherwise></c:choose></td><td><my:quoteStatus status="${q.status}"/></td></tr></c:forEach><c:if test="${empty quotes}"><tr><td colspan="5" class="empty-cell">견적 요청이 없습니다.</td></tr></c:if></tbody></table></div></section>
</div>
</main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script></body></html>
