<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>구매 발주 | 앙사모 ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/purchase.css"></head><body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace">
<section class="page-heading"><div><p class="eyebrow">PURCHASE ORDER</p><h1>구매 발주</h1><p>계약 확정 건의 발주 전달과 진행 상태를 조회합니다.</p></div></section>
<c:set var="orderCount" value="0"/>
<c:forEach items="${procurements}" var="p"><c:if test="${p.status == 'CONTRACTED' or p.status == 'ORDERED' or p.status == 'IN_PROGRESS' or p.status == 'SHIPPED' or p.status == 'RECEIVED' or p.status == 'CLOSED'}"><c:set var="orderCount" value="${orderCount + 1}"/></c:if></c:forEach>
<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">ORDER STATUS</p><h2>구매 발주 현황</h2></div><span class="list-count">${orderCount}건</span></div><div class="table-scroll"><table class="data-table purchase-wide-table"><thead><tr><th>발주</th><th>품목</th><th>협력회사</th><th>발주수량</th><th>단가</th><th>요구 납기</th><th>발주일시</th><th>현재 상태</th><th>상세</th></tr></thead><tbody>
<c:forEach items="${procurements}" var="p"><c:if test="${p.status == 'CONTRACTED' or p.status == 'ORDERED' or p.status == 'IN_PROGRESS' or p.status == 'SHIPPED' or p.status == 'RECEIVED' or p.status == 'CLOSED'}"><tr><td>PO-${p.procurementId}</td><td><c:out value="${p.itemName}"/></td><td><c:out value="${p.selectedVendorName}"/></td><td class="purchase-number">${p.orderQty} ${p.unit}</td><td class="purchase-number">${p.unitPrice}</td><td>${p.requiredDate}</td><td><c:out value="${p.orderedAt}" default="발주 전"/></td><td><span class="state-badge purchase-status ${fn:toLowerCase(p.status)}">${p.status}</span></td><td><a class="purchase-action-button" href="${pageContext.request.contextPath}/purchase/procurements/${p.procurementId}">${p.status == 'CONTRACTED' ? '발주 등록' : '확인'}</a></td></tr></c:if></c:forEach>
<c:if test="${orderCount == 0}"><tr><td colspan="9" class="empty-cell">진행 중인 구매 발주가 없습니다.</td></tr></c:if>
</tbody></table></div></section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script></body></html>
