<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<c:set var="pageTitle" value="${board.boardName}" scope="request"/>
<c:set var="breadcrumb" value="게시판 / ${board.boardName}" scope="request"/>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><c:out value="${board.boardName}"/> | ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"></head>
<body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace"><section class="page-heading"><div><p class="eyebrow">BOARD</p><h1><c:out value="${board.boardName}"/></h1></div><a class="primary-button" href="${pageContext.request.contextPath}/boards">게시판 목록</a></section>
<c:if test="${not empty success}"><div class="notice">${success}</div></c:if><c:if test="${not empty error}"><div class="notice error-notice">${error}</div></c:if>
<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">POSTS</p><h2>게시글</h2></div><span class="list-count">${posts.size()}건</span><a class="primary-button" href="${pageContext.request.contextPath}/boards/${board.boardId}/posts/new">글쓰기</a></div><div class="table-scroll"><table class="data-table admin-table"><thead><tr><th>제목</th><th>작성자</th><th>조회수</th><th>작성일</th></tr></thead><tbody>
<c:forEach var="post" items="${posts}"><tr><td><a href="${pageContext.request.contextPath}/boards/${board.boardId}/posts/${post.postId}"><c:out value="${post.title}"/></a></td><td><c:out value="${post.authorName}"/></td><td>${post.viewCount}</td><td><c:out value="${fn:substringBefore(post.createdAt, 'T')}"/></td></tr></c:forEach>
<c:if test="${empty posts}"><tr><td class="empty-cell" colspan="4">등록된 게시글이 없습니다.</td></tr></c:if></tbody></table></div>
<jsp:include page="/WEB-INF/views/common/pagination.jsp"/>
</section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script></body></html>
