<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="게시판 관리" scope="request"/>
<c:set var="breadcrumb" value="관리자 / 게시판 관리" scope="request"/>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>게시판 관리 | ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"></head>
<body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace"><section class="page-heading"><div><p class="eyebrow">ADMIN</p><h1>게시판 관리</h1><p>전체 게시판과 부서 게시판을 등록하고 관리합니다.</p></div></section>
<c:if test="${not empty success}"><div class="notice">${success}</div></c:if><c:if test="${not empty error}"><div class="notice error-notice">${error}</div></c:if>
<details class="panel admin-form-panel"><summary><div><p class="eyebrow">NEW BOARD</p><h2>게시판 등록</h2></div></summary><form class="admin-user-form" method="post" action="${pageContext.request.contextPath}/admin/boards"><input name="boardCode" placeholder="BOARD_CODE" pattern="[A-Za-z][A-Za-z0-9_]*" required><input name="boardName" placeholder="게시판명" required><select name="departmentId"><option value="">전체 게시판</option><c:forEach var="department" items="${departments}"><option value="${department.departmentId}"><c:out value="${department.departmentName}"/> 게시판</option></c:forEach></select><button class="primary-button" type="submit">등록</button></form></details>
<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">BOARD LIST</p><h2>전체 게시판</h2></div><div class="filter-chips">
	<a class="filter-chip ${empty status ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/boards">전체 <strong>${grandTotal}</strong></a>
	<a class="filter-chip ${status == 'active' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/boards?status=active">사용중 <strong>${activeCount}</strong></a>
	<a class="filter-chip ${status == 'suspended' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/boards?status=suspended">중지 <strong>${inactiveCount}</strong></a>
</div><input class="table-search" data-table-search="board-table" placeholder="코드, 게시판명 검색"></div><div class="table-scroll"><table class="data-table admin-table" id="board-table"><thead><tr><th>ID</th><th>코드</th><th>게시판명</th><th>대상 부서</th><th>상태</th><th>등록일</th><th>관리</th></tr></thead><tbody>
<c:forEach var="board" items="${boards}"><tr><td>${board.boardId}</td><td><c:out value="${board.boardCode}"/></td><td><input form="board-${board.boardId}" name="boardName" value="<c:out value='${board.boardName}'/>" required></td><td><c:choose><c:when test="${empty board.departmentId}">전체</c:when><c:otherwise><c:out value="${board.departmentName}"/></c:otherwise></c:choose></td><td><select form="board-${board.boardId}" name="active"><option value="true" ${board.active ? 'selected' : ''}>사용</option><option value="false" ${not board.active ? 'selected' : ''}>중지</option></select></td><td><c:out value="${board.createdAt}"/></td><td class="row-actions"><a class="icon-btn" title="게시글보기" href="${pageContext.request.contextPath}/admin/boards/${board.boardId}"><span class="material-symbols-outlined">forum</span></a><form id="board-${board.boardId}" method="post" action="${pageContext.request.contextPath}/admin/boards/${board.boardId}"><button class="icon-btn" type="submit" title="수정"><span class="material-symbols-outlined">save</span></button></form><form method="post" action="${pageContext.request.contextPath}/admin/boards/${board.boardId}/deactivate"><button class="icon-btn danger" type="submit" title="사용중지"><span class="material-symbols-outlined">block</span></button></form></td></tr></c:forEach>
<c:if test="${empty boards}"><tr><td class="empty-cell" colspan="7">등록된 게시판이 없습니다.</td></tr></c:if></tbody></table></div></section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script><script src="${pageContext.request.contextPath}/resources/js/admin-filter.js"></script></body></html>
