<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="부서 관리" scope="request"/>
<c:set var="breadcrumb" value="관리자 / 부서 관리" scope="request"/>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>부서 관리 | ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"></head>
<body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace"><section class="page-heading"><div><p class="eyebrow">ADMIN</p><h1>부서 관리</h1><p>부서를 등록하고 코드, 이름, 상태를 관리합니다.</p></div></section>
<c:if test="${not empty success}"><div class="notice">${success}</div></c:if><c:if test="${not empty error}"><div class="notice error-notice">${error}</div></c:if>
<details class="panel admin-form-panel"><summary><div><p class="eyebrow">NEW DEPARTMENT</p><h2>부서 등록</h2></div></summary><form class="admin-user-form department-form" method="post" action="${pageContext.request.contextPath}/admin/departments"><input name="departmentCode" placeholder="DEPARTMENT_CODE" pattern="[A-Za-z][A-Za-z0-9_]*" required><input name="departmentName" placeholder="부서명" required><button class="primary-button" type="submit">등록</button></form></details>
<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">DEPARTMENT LIST</p><h2>전체 부서</h2></div><div class="filter-chips">
	<a class="filter-chip ${empty status ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/departments">전체 <strong>${grandTotal}</strong></a>
	<a class="filter-chip ${status == 'active' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/departments?status=active">사용중 <strong>${activeCount}</strong></a>
	<a class="filter-chip ${status == 'suspended' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/departments?status=suspended">정지 <strong>${inactiveCount}</strong></a>
</div><input class="table-search" data-table-search="department-table" placeholder="코드, 부서명 검색"></div><div class="table-scroll"><table class="data-table admin-table" id="department-table"><thead><tr><th>ID</th><th>부서 코드</th><th>부서명</th><th>상태</th><th>등록일</th><th>관리</th></tr></thead><tbody>
<c:forEach var="department" items="${departments}"><tr><td>${department.departmentId}</td><td><c:out value="${department.departmentCode}"/></td><td><input form="department-${department.departmentId}" name="departmentName" value="<c:out value='${department.departmentName}'/>" required></td><td><select form="department-${department.departmentId}" name="active"><option value="true" ${department.active ? 'selected' : ''}>사용</option><option value="false" ${not department.active ? 'selected' : ''}>정지</option></select></td><td><c:out value="${department.createdAt}"/></td><td class="row-actions"><a class="icon-btn" title="상세보기" href="${pageContext.request.contextPath}/admin/departments/${department.departmentId}"><span class="material-symbols-outlined">visibility</span></a><form id="department-${department.departmentId}" method="post" action="${pageContext.request.contextPath}/admin/departments/${department.departmentId}"><button class="icon-btn" type="submit" title="수정"><span class="material-symbols-outlined">save</span></button></form><form method="post" action="${pageContext.request.contextPath}/admin/departments/${department.departmentId}/deactivate"><button class="icon-btn danger" type="submit" title="비활성화"><span class="material-symbols-outlined">block</span></button></form></td></tr></c:forEach>
<c:if test="${empty departments}"><tr><td class="empty-cell" colspan="6">등록된 부서가 없습니다.</td></tr></c:if></tbody></table></div></section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script><script src="${pageContext.request.contextPath}/resources/js/admin-filter.js"></script></body></html>
