<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="게시글 관리" scope="request"/>
<c:set var="breadcrumb" value="관리자 / 게시글 관리" scope="request"/>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>게시글 관리 | ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"></head>
<body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace"><section class="page-heading"><div><p class="eyebrow">ADMIN</p><h1>게시글 관리</h1><p>모든 게시판의 게시글을 조회하고 사용 중지할 수 있습니다.</p></div></section>
<c:if test="${not empty success}"><div class="notice">${success}</div></c:if><c:if test="${not empty error}"><div class="notice error-notice">${error}</div></c:if>
<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">POST LIST</p><h2>전체 게시글</h2></div><div class="filter-chips">
	<a class="filter-chip ${empty status ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/posts">전체 <strong>${grandTotal}</strong></a>
	<a class="filter-chip ${status == 'active' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/posts?status=active">사용중 <strong>${activeCount}</strong></a>
	<a class="filter-chip ${status == 'suspended' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/posts?status=suspended">중지 <strong>${inactiveCount}</strong></a>
</div><input class="table-search" data-table-search="post-table" placeholder="게시판, 제목 검색"></div><div class="table-scroll"><table class="data-table admin-table" id="post-table"><thead><tr><th>ID</th><th>게시판</th><th>제목</th><th>작성자</th><th>조회수</th><th>상태</th><th>작성일</th><th>관리</th></tr></thead><tbody>
<c:forEach var="post" items="${posts}"><tr><td>${post.postId}</td><td><c:out value="${post.boardName}"/></td><td><a href="${pageContext.request.contextPath}/admin/posts/${post.postId}"><c:out value="${post.title}"/></a></td><td><c:out value="${post.authorName}"/></td><td>${post.viewCount}</td><td><span class="state-badge ${post.active ? 'enabled' : 'disabled'}">${post.active ? '사용' : '중지'}</span></td><td><c:out value="${post.createdAt}"/></td><td class="row-actions"><a class="icon-btn" title="상세" href="${pageContext.request.contextPath}/admin/posts/${post.postId}"><span class="material-symbols-outlined">visibility</span></a><form method="post" action="${pageContext.request.contextPath}/admin/posts/${post.postId}/deactivate"><button class="icon-btn danger" type="submit" title="사용중지"><span class="material-symbols-outlined">block</span></button></form></td></tr></c:forEach>
<c:if test="${empty posts}"><tr><td class="empty-cell" colspan="8">등록된 게시글이 없습니다.</td></tr></c:if></tbody></table></div>
<jsp:include page="/WEB-INF/views/common/pagination.jsp"/>
</section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script><script src="${pageContext.request.contextPath}/resources/js/admin-filter.js"></script></body></html>
