<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="사용자 관리" scope="request"/>
<c:set var="breadcrumb" value="관리자 / 사용자 관리" scope="request"/>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>사용자 관리 | ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"></head>
<body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace"><section class="page-heading"><div><p class="eyebrow">ADMIN</p><h1>사용자 관리</h1><p>계정을 등록하고 소속, 권한, 상태를 관리합니다.</p></div></section>
<c:if test="${not empty success}"><div class="notice">${success}</div></c:if><c:if test="${not empty error}"><div class="notice error-notice">${error}</div></c:if>

<details class="panel admin-form-panel"><summary><div><p class="eyebrow">NEW USER</p><h2>사용자 등록</h2></div></summary><form class="admin-user-form" method="post" action="${pageContext.request.contextPath}/admin/users"><input name="loginId" placeholder="로그인 아이디" required><input type="password" name="password" placeholder="비밀번호" required><input name="userName" placeholder="이름" required><select name="departmentId"><option value="">부서 없음</option><c:forEach var="department" items="${departments}"><c:if test="${department.active}"><option value="${department.departmentId}"><c:out value="${department.departmentName}"/></option></c:if></c:forEach></select><select name="vendorId"><option value="">협력회사 없음</option><c:forEach var="vendor" items="${vendors}"><option value="${vendor.vendorId}"><c:out value="${vendor.vendorName}"/></option></c:forEach></select><select name="role"><option value="MEMBER">MEMBER</option><option value="ADMIN">ADMIN</option><option value="VENDOR">VENDOR</option></select><button class="primary-button" type="submit">등록</button></form></details>

<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">USER LIST</p><h2>전체 사용자</h2></div><div class="filter-chips">
	<a class="filter-chip ${empty status ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/users">전체 <strong>${grandTotal}</strong></a>
	<a class="filter-chip ${status == 'active' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/users?status=active">사용중 <strong>${activeCount}</strong></a>
	<a class="filter-chip ${status == 'suspended' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/users?status=suspended">정지 <strong>${inactiveCount}</strong></a>
</div><input class="table-search" data-table-search="user-table" placeholder="아이디, 이름, 부서 검색"></div><div class="table-scroll"><table class="data-table admin-table" id="user-table"><thead><tr><th>ID</th><th>아이디</th><th>이름</th><th>부서</th><th>협력회사</th><th>권한</th><th>상태</th><th>새 비밀번호</th><th>관리</th></tr></thead><tbody>
<c:forEach var="user" items="${users}"><tr><td>${user.userId}</td><td><c:out value="${user.loginId}"/></td><td><input form="user-${user.userId}" name="userName" value="<c:out value='${user.userName}'/>" required></td><td><select form="user-${user.userId}" name="departmentId"><option value="">부서 없음</option><c:forEach var="department" items="${departments}"><option value="${department.departmentId}" ${user.departmentId == department.departmentId ? 'selected' : ''}><c:out value="${department.departmentName}"/></option></c:forEach></select></td><td><select form="user-${user.userId}" name="vendorId"><option value="">없음</option><c:forEach var="vendor" items="${vendors}"><option value="${vendor.vendorId}" ${user.vendorId == vendor.vendorId ? 'selected' : ''}><c:out value="${vendor.vendorName}"/></option></c:forEach></select></td><td><select form="user-${user.userId}" name="role"><option value="MEMBER" ${user.role == 'MEMBER' ? 'selected' : ''}>MEMBER</option><option value="ADMIN" ${user.role == 'ADMIN' ? 'selected' : ''}>ADMIN</option><option value="VENDOR" ${user.role == 'VENDOR' ? 'selected' : ''}>VENDOR</option></select></td><td><select form="user-${user.userId}" name="active"><option value="true" ${user.active ? 'selected' : ''}>사용</option><option value="false" ${not user.active ? 'selected' : ''}>정지</option></select></td><td><input form="user-${user.userId}" type="password" name="password" placeholder="유지"></td><td class="row-actions"><a class="icon-btn" title="상세보기" href="${pageContext.request.contextPath}/admin/users/${user.userId}"><span class="material-symbols-outlined">visibility</span></a><form id="user-${user.userId}" method="post" action="${pageContext.request.contextPath}/admin/users/${user.userId}"><button class="icon-btn" type="submit" title="수정"><span class="material-symbols-outlined">save</span></button></form><form method="post" action="${pageContext.request.contextPath}/admin/users/${user.userId}/deactivate"><button class="icon-btn danger" type="submit" title="비활성화"><span class="material-symbols-outlined">block</span></button></form></td></tr></c:forEach>
<c:if test="${empty users}"><tr><td class="empty-cell" colspan="9">등록된 사용자가 없습니다.</td></tr></c:if></tbody></table></div>
<jsp:include page="/WEB-INF/views/common/pagination.jsp"/>
</section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script><script src="${pageContext.request.contextPath}/resources/js/admin-filter.js"></script></body></html>
