<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="협력회사 관리" scope="request"/>
<c:set var="breadcrumb" value="관리자 / 협력회사 관리" scope="request"/>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>협력회사 관리 | ERP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&family=Noto+Sans+KR:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/common.css"></head>
<body><jsp:include page="/WEB-INF/views/common/sidebar.jsp"/><div class="app-shell"><jsp:include page="/WEB-INF/views/common/header.jsp"/><main class="workspace"><section class="page-heading"><div><p class="eyebrow">ADMIN</p><h1>협력회사 관리</h1><p>협력회사 코드와 회사명을 관리합니다.</p></div></section><c:if test="${not empty success}"><div class="notice">${success}</div></c:if><c:if test="${not empty error}"><div class="notice error-notice">${error}</div></c:if>
<details class="panel admin-form-panel"><summary><div><p class="eyebrow">NEW VENDOR</p><h2>협력회사 등록</h2></div></summary><form class="admin-user-form department-form" method="post" action="${pageContext.request.contextPath}/admin/vendors"><input name="vendorCode" placeholder="VENDOR_CODE" pattern="[A-Za-z0-9_-]+" required><input name="vendorName" placeholder="협력회사명" required><button class="primary-button" type="submit">등록</button></form></details>
<section class="panel table-panel"><div class="panel-header"><div><p class="eyebrow">VENDOR LIST</p><h2>전체 협력회사</h2></div><div class="filter-chips">
	<a class="filter-chip ${empty status ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/vendors">전체 <strong>${grandTotal}</strong></a>
	<a class="filter-chip ${status == 'active' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/vendors?status=active">거래중 <strong>${activeCount}</strong></a>
	<a class="filter-chip ${status == 'suspended' ? 'current' : ''}" href="${pageContext.request.contextPath}/admin/vendors?status=suspended">거래중지 <strong>${inactiveCount}</strong></a>
</div><input class="table-search" data-table-search="vendor-table" placeholder="코드, 회사명 검색"></div><div class="table-scroll"><table class="data-table admin-table" id="vendor-table"><thead><tr><th>코드</th><th>회사명</th><th>상태</th><th>등록일</th><th>관리</th></tr></thead><tbody><c:forEach var="vendor" items="${vendors}"><tr><td><a href="${pageContext.request.contextPath}/admin/vendors/${vendor.vendorId}"><c:out value="${vendor.vendorCode}"/></a></td><td><input form="vendor-${vendor.vendorId}" name="vendorName" value="<c:out value='${vendor.vendorName}'/>" required></td><td><span class="state-badge ${vendor.active ? 'enabled' : 'disabled'}">${vendor.active ? '거래중' : '거래중지'}</span></td><td><c:out value="${vendor.createdAt}"/></td><td class="row-actions"><a class="icon-btn" title="상세보기" href="${pageContext.request.contextPath}/admin/vendors/${vendor.vendorId}"><span class="material-symbols-outlined">visibility</span></a><form id="vendor-${vendor.vendorId}" method="post" action="${pageContext.request.contextPath}/admin/vendors/${vendor.vendorId}"><button class="icon-btn" type="submit" title="수정"><span class="material-symbols-outlined">save</span></button></form></td></tr></c:forEach><c:if test="${empty vendors}"><tr><td class="empty-cell" colspan="5">등록된 협력회사가 없습니다.</td></tr></c:if></tbody></table></div>
<jsp:include page="/WEB-INF/views/common/pagination.jsp"/>
</section></main></div><script src="${pageContext.request.contextPath}/resources/js/common.js"></script><script src="${pageContext.request.contextPath}/resources/js/admin-filter.js"></script></body></html>
